appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: YJrufnepyt6F+vt8jLImuK8gdeh+mV9wPM7vH1ce/zOZD6+Z7/rEX9zQNWZSVlIiOPlSRoip/PSPSO5l+MftW6H6NziYh2LjwO3+cYs4z5K/0etQCdRKgPEKpPSqjzwew8HJdicGRfge0uUmZh2MmYR1tAnsu3deNhY2B/263LNRmmHrGt9h+l4DKd6X21uNAx801oGnjNelA/czOXHqnaK/UnNn0+g7AXEFw2yqAbsTE6FypglLgKzA5kV/UL6JD/Chkql3FtqdEG3DMQnEurtJPzKmVSROGXuG+S0469D3Qk54sh4dxNglrrW4Uozp5LgUJ8ovQHAYiZcdb3NRD0Hg88yZOJPa3WgZC1b1fbeae1neQrIEZ72Agh2Xweiw4BmlhOOB2oqoPCncbhVgGzOF6VOT9VA8ZmZAuVG1y4ljk1NN8eO88ImptSrGgOLVOMxI+LnW8FWmS6UYZsffk886MIcx74kmI2L8Yk1oIdmvL9uHbJ+/eEbodrkjETkhYvOqr54filacWxlavbMGq1AZqNhyt85JSt0CzfJY+OIq1e53D7342gSa+SlKh0VQGcB1nlbKiFizY1K3OY7PqLWVwcKm8d191iIDDvprU7ER/RXNEycNNdbjWjFx5qMLuuzTRpexQ8RpYmxyRCybV4n/va43Z7EEp0Bs9szv8/c=
